version: '3.9'

services:

  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db-test

  db-test:
    image: postgres:16.2
    restart: always
    container_name: beautyhouse-test
    shm_size: 128mb
    ports:
    - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: beautyhouse-test


  
